//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinDynamic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public string CodigoEmpleado { get; set; }
        public string Nombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public Nullable<decimal> SalarioMensual { get; set; }
        public Nullable<int> TipoSalario { get; set; }
        public Nullable<int> CodigoPlanilla { get; set; }
        public Nullable<int> CodigoCargo { get; set; }
        public Nullable<int> CodigoNivel { get; set; }
        public Nullable<int> CodigoHorario { get; set; }
        public Nullable<int> CodigoArea { get; set; }
        public Nullable<int> CodigoDepartamento { get; set; }
        public int CodigoSucursal { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string LugardeNacimiento { get; set; }
        public string Codigo_Clasif01 { get; set; }
        public string Codigo_Clasif02 { get; set; }
        public string Codigo_Clasif03 { get; set; }
        public string Codigo_Clasif04 { get; set; }
        public string Codigo_Clasif05 { get; set; }
        public string Codigo_Clasif06 { get; set; }
        public string NombreConyuge { get; set; }
        public string NoInss { get; set; }
        public string NoRUC { get; set; }
        public string TelHabitacion { get; set; }
        public string TelefonoCelular { get; set; }
        public string DirHabitacion { get; set; }
        public string TelOficina { get; set; }
        public string FaxOficina { get; set; }
        public string DirOficina { get; set; }
        public string email { get; set; }
        public string Login { get; set; }
        public int NoHijos { get; set; }
        public string RutaFoto { get; set; }
        public Nullable<int> Sexo { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<int> CodigoMotivoA { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<int> TipoEstado { get; set; }
        public Nullable<int> FormaPago { get; set; }
        public Nullable<int> TipoMoneda { get; set; }
        public string CtaxCobrar { get; set; }
        public string ApartadoPostal { get; set; }
        public Nullable<int> EstadoCivil { get; set; }
        public Nullable<System.DateTime> FechaAniversario { get; set; }
        public string Cedula { get; set; }
        public decimal IngGravableInss { get; set; }
        public decimal IngGravableIR { get; set; }
        public bool isSubsidio { get; set; }
        public int NAntiguedad { get; set; }
        public float PorcAntiguedad { get; set; }
        public string TipoEmpleo { get; set; }
        public int CodigoNacionalidad { get; set; }
        public decimal Acumulado { get; set; }
        public decimal AcumuladoIr { get; set; }
        public decimal IngGravableSubsidio { get; set; }
        public string NombreExportacion { get; set; }
        public decimal SalarioINSS { get; set; }
        public bool isPeriodoPrueba { get; set; }
        public Nullable<System.DateTime> FechaPeriodoPrueba { get; set; }
        public int CodigoTurno { get; set; }
        public bool isEmpleadoIndirecto { get; set; }
        public decimal IngGravablesInss_Local { get; set; }
        public decimal IngGravablesInss_Dolar { get; set; }
        public decimal IngGravablesIR_Local { get; set; }
        public decimal IngGravablesIR_Dolar { get; set; }
        public decimal IngGravablesSubsidio_Local { get; set; }
        public decimal IngGravablesSubsidio_Dolar { get; set; }
        public decimal IngAdicionales_Local { get; set; }
        public decimal IngAdicionales_Dolar { get; set; }
        public decimal InssPeriodo_Local { get; set; }
        public decimal InssPeriodo_Dolar { get; set; }
        public decimal InssPeriodoAdicional_Local { get; set; }
        public decimal InssPeriodoAdicional_Dolar { get; set; }
        public decimal InssPatronalPeriodo_Local { get; set; }
        public decimal InssPatronalPeriodo_Dolar { get; set; }
        public decimal InatecPeriodo_Local { get; set; }
        public decimal InatecPeriodo_Dolar { get; set; }
        public int AnioFiscal_SaldoInicial { get; set; }
        public decimal AcumuladoDev_SaldoInicial { get; set; }
        public decimal AcumuladoIR_SaldoInicial { get; set; }
        public int PeriodosProyectar_SaldoInicial { get; set; }
        public int PeriodosNoLaborados_SaldoInicial { get; set; }
        public decimal SalarioInssPorSubsidio { get; set; }
        public string Pais_Nacimiento { get; set; }
        public string Departamento_Nacimiento { get; set; }
        public string Municipio_Nacimiento { get; set; }
        public string Departamento_Actual { get; set; }
        public string Municipio_Actual { get; set; }
        public decimal IR_Fijo { get; set; }
        public decimal IngGravablesInss_LocalExtra { get; set; }
        public decimal IngGravablesInss_DolarExtra { get; set; }
        public decimal InssPeriodo_LocalExtra { get; set; }
        public decimal InssPeriodo_DolarExtra { get; set; }
        public decimal InssPatronalPeriodo_LocalExtra { get; set; }
        public decimal InssPatronalPeriodo_DolarExtra { get; set; }
        public decimal InatecPeriodo_LocalExtra { get; set; }
        public decimal InatecPeriodo_DolarExtra { get; set; }
        public decimal IngGravablesIR_LocalExtra { get; set; }
        public decimal IngGravablesIR_DolarExtra { get; set; }
    }
}
